import { Inject, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type {
  OperationalComponent,
  OperationalHealth,
} from '@logistics-globe/shared';
import type { RuntimeEnvironment } from '../../config/environment.js';
import { PrismaService } from '../../infrastructure/database/prisma.service.js';
import { MongoService } from '../../infrastructure/database/mongo.service.js';
import { functionalHealth } from '../../infrastructure/observability/metrics.js';
@Injectable()
export class OperationalHealthService {
  private cached?: OperationalHealth;
  private flight?: Promise<OperationalHealth>;
  constructor(
    @Inject(PrismaService) private readonly prisma: PrismaService,
    @Inject(MongoService) private readonly mongo: MongoService,
    @Inject(ConfigService)
    private readonly config: ConfigService<RuntimeEnvironment, true>,
  ) {}
  inspect(): Promise<OperationalHealth> {
    if (
      this.cached &&
      Date.now() - new Date(this.cached.checkedAt).getTime() < 15000
    )
      return Promise.resolve(this.cached);
    if (this.flight) return this.flight;
    this.flight = this.probe()
      .then((value) => (this.cached = value))
      .finally(() => {
        this.flight = undefined;
      });
    return this.flight;
  }
  private async component(
    name: OperationalComponent['name'],
    critical: boolean,
    read: () => Promise<{
      status: OperationalComponent['status'];
      reason: string;
    }>,
  ): Promise<OperationalComponent> {
    const start = performance.now();
    let value: { status: OperationalComponent['status']; reason: string };
    let timeout: ReturnType<typeof setTimeout> | undefined;
    try {
      value = await Promise.race([
        read(),
        new Promise<never>((_, reject) => {
          timeout = setTimeout(() => reject(new Error('Probe timeout')), 1500);
        }),
      ]);
    } catch {
      value = {
        status: 'unavailable',
        reason: 'Read-only probe failed or timed out',
      };
    } finally {
      if (timeout) clearTimeout(timeout);
    }
    functionalHealth.set(
      { component: name },
      value.status === 'operational'
        ? 1
        : value.status === 'unavailable'
          ? 0
          : 0.5,
    );
    return {
      name,
      critical,
      ...value,
      checkedAt: new Date().toISOString(),
      latencyMs: Math.round((performance.now() - start) * 100) / 100,
    };
  }
  private async probe(): Promise<OperationalHealth> {
    const components = await Promise.all([
      this.component('inventory-module', true, async () => {
        await this.prisma.inventoryItem.findFirst({
          select: {
            id: true,
            quantity: true,
            threshold: { select: { minimumQuantity: true } },
          },
        });
        return {
          status: 'operational',
          reason: 'Inventory module read path responds; not an external WMS',
        };
      }),
      this.component('routing', false, async () => {
        const origin = this.config.get('ROUTING_URL', { infer: true }),
          path = this.config.get('ROUTING_HEALTH_PATH', { infer: true });
        if (!origin)
          return {
            status: 'not-configured',
            reason: 'No approved routing provider configured',
          };
        if (!path)
          return {
            status: 'unknown',
            reason:
              'No approved non-billable health path; no route generated by probe',
          };
        const response = await fetch(new URL(path, origin), {
          method: 'HEAD',
          signal: AbortSignal.timeout(1200),
          redirect: 'error',
        });
        return response.ok
          ? {
              status: 'operational',
              reason: 'Configured provider read-only health probe responded',
            }
          : {
              status: 'unavailable',
              reason: 'Provider health probe returned an error',
            };
      }),
      this.component('gps-ingestion', false, async () => {
        if (!this.config.get('GPS_INGEST_TOKEN', { infer: true }))
          return {
            status: 'not-configured',
            reason: 'GPS integration disabled',
          };
        const collection = await this.mongo.collection<{
          observedAt: string;
          receivedAt: string;
        }>('vehicle_telemetry');
        const last = await collection.findOne(
          {
            vehicleId: {
              $in: this.config.get('GPS_ALLOWED_VEHICLE_IDS', { infer: true }),
            },
          },
          { sort: { receivedAt: -1 }, projection: { receivedAt: 1 } },
        );
        if (!last)
          return {
            status: 'unknown',
            reason: 'No observation received for scoped devices',
          };
        return Date.now() - new Date(last.receivedAt).getTime() > 120000
          ? {
              status: 'degraded',
              reason:
                'Scoped ingestion stale; no inference that vehicles stopped',
            }
          : {
              status: 'operational',
              reason:
                'Recent durable observation; physical device validity unverified',
            };
      }),
      this.component('erp-wms-reference', false, async () => {
        const last = await this.prisma.integrationReceipt.findFirst({
          where: { source: 'reference-stock' },
          orderBy: { createdAt: 'desc' },
          select: { status: true, createdAt: true },
        });
        if (!last)
          return {
            status: 'unknown',
            reason:
              'Local reference adapter available; no accepted reference exchange',
          };
        return last.status === 'accepted'
          ? {
              status: 'operational',
              reason:
                'Last local reference stock exchange accepted; real compatibility unverified',
            }
          : {
              status: 'degraded',
              reason: 'Last reference exchange needs reconciliation',
            };
      }),
    ]);
    return { checkedAt: new Date().toISOString(), components };
  }
}
